# Weeder configuration file
# https://github.com/ndmitchell/weeder
##########################

- message:
  - name: Weeds exported
  - identifier: [ParseMode', defaultParseMode', isAssocLeft, isAssocNone] # Last two weeder bugs?

- message:
  - name: Redundant build-depends entry
  - depends: [ghc-lib, ghc, ghc-boot-th, ghc-boot] # Only some subset is supported
