# Because hsdev hasn't upgraded we need our own Snapshot, see:
# * https://github.com/commercialhaskell/stackage/issues/4673
# * https://github.com/commercialhaskell/stackage/issues/4731
resolver: nightly-2019-08-27
packages: [.]
extra-deps: [ghc-lib-parser-8.8.1]
