resolver: lts-14.20 # ghc-8.6.5
packages:
  - .
extra-deps:
  - ghc-lib-parser-8.10.1.20200523
  - ghc-lib-parser-ex-8.10.0.12
# To test hlint against experimental builds of ghc-lib-parser-ex,
# modify extra-deps like this:
#  - archive: /users/shaynefletcher/project/ghc-lib-parser-ex.git/ghc-lib-parser-ex-8.10.0.13.tar.gz
#    sha256: "0000000000000000000000000000000000000000000000000000000000000000
#  - extra-1.7.3
ghc-options: {"$locals": -ddump-to-file -ddump-hi -Werror=unused-imports -Werror=unused-top-binds -Werror=orphans}
# Enabling this stanza forces both hlint and ghc-lib-parser-ex to
# depend on ghc-lib-parser.
# flags:
#   hlint:
#     ghc-lib: true
#   ghc-lib-parser-ex:
#     auto: false
#     no-ghc-lib: false
