# For hlint/ghc-9.10.*, the minimum build compiler is ghc-9.6.1.
resolver:  lts-22.21 # ghc-9.6.5
allow-newer: True
packages:
  - .
extra-deps:
  - github: shayne-fletcher/text-short
    commit: "qualify-foldl"
  - ghc-lib-parser-9.10.1.20240511
  - ghc-lib-parser-ex-9.10.0.0
ghc-options: {"$locals": -ddump-to-file -ddump-hi -Werror=unused-imports -Werror=unused-local-binds -Werror=unused-top-binds -Werror=orphans -Werror=prepositive-qualified-module}
