# For hlint/ghc-9.6.*, the minimum build compiler is ghc-9.2.2 (ghc-9.2.1 was a broken release). 9.2.2 exhibits the "'ffitarget_x86.h' file not found" problem on macOS.  in this case, build with invoke `C_INCLUDE_PATH="$(xcrun --show-sdk-path)"/usr/include/ffi stack build`.
resolver:  nightly-2023-03-12 # ghc-9.4.4

packages:
  - .

extra-deps:
  - ghc-lib-parser-9.6.1.20230312
  - ghc-lib-parser-ex-9.6.0.0
# To test hlint against experimental builds of ghc-lib-parser-ex,
# modify extra-deps like this:
#  - archive: /users/shayne/project/ghc-lib-parser-ex/ghc-lib-parser-ex-8.10.0.18.tar.gz
#    sha256: "0000000000000000000000000000000000000000000000000000000000000000"

ghc-options: {"$locals": -ddump-to-file -ddump-hi -Werror=unused-imports -Werror=unused-local-binds -Werror=unused-top-binds -Werror=orphans -Werror=prepositive-qualified-module}

# Enabling this stanza forces both hlint and ghc-lib-parser-ex to
# depend on ghc-lib-parser.
# flags:
#   hlint:
#     ghc-lib: true
#   ghc-lib-parser-ex:
#     auto: false
#     no-ghc-lib: false
