resolver: nightly-2019-08-07 # Don't roll to an 8.8.1 or 8.8.2 resolver because of the Windows linker bug
packages: [.]
extra-deps:
  - ghc-lib-parser-8.8.2.20200205
  - ghc-lib-parser-ex-8.8.4.0
  - haskell-src-exts-1.23.0
ghc-options:
    "$locals": -Wunused-imports -Worphans -Wunused-top-binds -Wunused-local-binds -Wincomplete-patterns
# If the compiler is 8.8.*, by default, ghc-lib-parser won't be a
# dependency (rather ghc will). Enabling this stanza forces both hlint
# and ghc-lib-parser-ex to depend on ghc-lib-parser int his case.
# flags:
#   hlint:
#     ghc-lib: true
#   ghc-lib-parser-ex:
#     ghc-lib: true
